[package]
name = "weblogviz"
version = "0.2.0"
authors = ["Puneeth Chaganti <punchagan@muse-amuse.in>"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1.1.0"
chrono = "0.4.6"
threadpool = "1.7.1"
clap = {features = ["yaml"], version ="2.32.0"}
flate2 = "1.0.4"